name: patname
version: "2.10"
summary: "generate pronouncable, perhaps even memorable, pat names"
description: |
 This utility will generate pat names, consisting of a random
 combination of an adverb, adjective, and "patrick".  These are
 useful for unique hostnames, VMs, or containers, for instance.
confinement: strict
icon: icons/petname.png

apps:
  patname:
    command: bin/patname

parts:
  wrapper:
    plugin: dump
    source: usr/
  mypackages:
    plugin: nil
    stage-packages:
    - coreutils
